version: '3'

services:
  app:
    build:
      context: "./"
      dockerfile: Dockerfile
    container_name: 'demo-app'
    hostname: demo-app
    ports:
      - '8080:8080'
    networks:
      - backend
    restart: always 

  prometheus:
    image: prom/prometheus
    container_name: 'prometheus'
    hostname: prometheus
    ports:
      - '9090:9090'
    networks:
      - backend
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus-data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app

  grafana:
    image: grafana/grafana-enterprise
    container_name: 'grafana'
    hostname: grafana
    restart: unless-stopped
    user: '0' # if you are running as root then set it to 0. else find the right id with the id -u command
    networks:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/conf/provisioning/dashboards/:/usr/share/grafana/conf/provisioning/dashboards/ #주의! - os마다, grafana 버전마다 docker container에서 volume mapping해줘야하는 장소가 달라질 수 있다. 현재 config는 mac m1 기준이다. 
      - ./grafana/conf/provisioning/datasources/:/usr/share/grafana/conf/provisioning/datasources/
      - ./grafana/grafana_data/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

  load-test:
    build:
      context: "./load-test"
      dockerfile: Dockerfile
    container_name: 'load-test'
    hostname: load-test
    networks:
      - backend
    depends_on:
      - grafana
      - app

networks:
  backend:

volumes:
  prometheus_data: {}
