# config file version
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: 'my Prometheus metrics from springboot app'
    orgId: 1 # <int> Org id. Default to 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
